version: "3.8"

services:
  gateway:
    build: ./reshaka-gateway-service
    ports:
      - "8200:8200"
    depends_on:
      - tasks-service
      - usb
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  tasks-service:
    build: ./reshaka-task-service
  # internal port 8100

  usb:
    build: ./reshaka-admin-service
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/app
    command:
      [ "./wait-for-it.sh", "database:5432", "--", "sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload" ]

  # internal port 8102

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: reshaka
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-db:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: